package com.example.c001apk.util

import com.example.c001apk.R
import com.example.c001apk.logic.model.ItemBean

object Emoji {

    fun initEmoji(pageSize: Int): List<List<ItemBean>> {
        val data: MutableList<ItemBean> = ArrayList()
        val maps: MutableList<List<ItemBean>> = ArrayList()
        data.add(ItemBean("[doge]", R.drawable.coolapk_emotion_37_doge))
        data.add(ItemBean("[doge原谅ta]", R.drawable.coolapk_emotion_58_dogeyuanliangta))
        data.add(ItemBean("[doge呵斥]", R.drawable.coolapk_emotion_57_dogehechi))
        data.add(ItemBean("[doge笑哭]", R.drawable.coolapk_emotion_56_dogexiaoku))
        data.add(ItemBean("[ok]", R.drawable.coolapk_emotion_30_ok))
        data.add(ItemBean("[py交易]", R.drawable.coolapk_emotion_101_pyjiaoyi))
        data.add(ItemBean("[qqdoge]", R.drawable.coolapk_emotion_100_qqdoge))
        data.add(ItemBean("[t耐克嘴]", R.drawable.coolapk_emotion_105))
        data.add(ItemBean("[yyds]", R.drawable.coolapk_emotion_1027))
        data.add(ItemBean("[下次一定]", R.drawable.coolapk_emotion_1029))
        data.add(ItemBean("[不开心]", R.drawable.coolapk_emotion_108))
        data.add(ItemBean("[二哈]", R.drawable.coolapk_emotion_59_erha))
        data.add(ItemBean("[二哈盯]", R.drawable.coolapk_emotion_95_erhading))
        data.add(ItemBean("[亲亲]", R.drawable.coolapk_emotion_20_qinqin))
        data.add(ItemBean("[假笑]", R.drawable.coolapk_emotion_1014))
        data.add(ItemBean("[偷看]", R.drawable.coolapk_emotion_1015))
        data.add(ItemBean("[傲慢]", R.drawable.coolapk_emotion_10_aoman))
        data.add(ItemBean("[再见]", R.drawable.coolapk_emotion_25_zaijian))
        data.add(ItemBean("[凋谢]", R.drawable.coolapk_emotion_42_diaoxie))
        data.add(ItemBean("[列文虎克]", R.drawable.coolapk_emotion_1023_liewenhuke))
        data.add(ItemBean("[c001apk]", R.drawable.ic_backspace))

        //2
        data.add(ItemBean("[发呆]", R.drawable.coolapk_emotion_102_fadai))
        data.add(ItemBean("[发怒]", R.drawable.coolapk_emotion_15_fanu))
        data.add(ItemBean("[受虐滑稽]", R.drawable.coolapk_emotion_64_shounuehuaji))
        data.add(ItemBean("[可怜]", R.drawable.coolapk_emotion_26_kelian))
        data.add(ItemBean("[可爱]", R.drawable.coolapk_emotion_5_keai))
        data.add(ItemBean("[吃瓜]", R.drawable.coolapk_emotion_51_chigua))
        data.add(ItemBean("[吐舌]", R.drawable.coolapk_emotion_17_tushe))
        data.add(ItemBean("[呲牙]", R.drawable.coolapk_emotion_3_ciya))
        data.add(ItemBean("[呵呵]", R.drawable.coolapk_emotion_7_hehe))
        data.add(ItemBean("[哈哈哈]", R.drawable.coolapk_emotion_1_hahaha))
        data.add(ItemBean("[哦吼吼]", R.drawable.coolapk_emotion_1017))
        data.add(ItemBean("[哼唧]", R.drawable.coolapk_emotion_1011))
        data.add(ItemBean("[喝茶]", R.drawable.coolapk_emotion_1016))
        data.add(ItemBean("[喝酒]", R.drawable.coolapk_emotion_52_hejiu))
        data.add(ItemBean("[喵喵]", R.drawable.coolapk_emotion_82_miaomiao))
        data.add(ItemBean("[喷]", R.drawable.coolapk_emotion_44_pen))
        data.add(ItemBean("[喷血]", R.drawable.coolapk_emotion_21_penxue))
        data.add(ItemBean("[嘿哈]", R.drawable.coolapk_emotion_32_heiha))
        data.add(ItemBean("[噗]", R.drawable.coolapk_emotion_53_pu))
        data.add(ItemBean("[坏笑]", R.drawable.coolapk_emotion_13_huaixiao))
        data.add(ItemBean("[c001apk]", R.drawable.ic_backspace))

        //3
        data.add(ItemBean("[墨镜滑稽]", R.drawable.coolapk_emotion_67_mojinghuaji))
        data.add(ItemBean("[夏阁艾迪之剑]", R.drawable.coolapk_emotion_1028))
        data.add(ItemBean("[头条通知书]", R.drawable.coolapk_emotion_1031))
        data.add(ItemBean("[委屈]", R.drawable.coolapk_emotion_47_weiqu))
        data.add(ItemBean("[害怕]", R.drawable.coolapk_emotion_1010))
        data.add(ItemBean("[害羞]", R.drawable.coolapk_emotion_97_haixiu))
        data.add(ItemBean("[小嘴滑稽]", R.drawable.coolapk_emotion_1013))
        data.add(ItemBean("[弱]", R.drawable.coolapk_emotion_28_ruo))
        data.add(ItemBean("[强]", R.drawable.coolapk_emotion_27_qiang))
        data.add(ItemBean("[微微一笑]", R.drawable.coolapk_emotion_48_weiweiyixiao))
        data.add(ItemBean("[微笑]", R.drawable.coolapk_emotion_6_weixiao))
        data.add(ItemBean("[心碎]", R.drawable.coolapk_emotion_50_xinsui))
        data.add(ItemBean("[惊讶]", R.drawable.coolapk_emotion_2_jingya))
        data.add(ItemBean("[感知不强]", R.drawable.coolapk_emotion_1025))
        data.add(ItemBean("[懒得理]", R.drawable.coolapk_emotion_107))
        data.add(ItemBean("[我最美]", R.drawable.coolapk_emotion_38_wozuimei))
        data.add(ItemBean("[托腮]", R.drawable.coolapk_emotion_16_tuosai))
        data.add(ItemBean("[抠鼻]", R.drawable.coolapk_emotion_19_koubi))
        data.add(ItemBean("[抱拳]", R.drawable.coolapk_emotion_29_baoquan))
        data.add(ItemBean("[挑眉坏笑]", R.drawable.coolapk_emotion_109))
        data.add(ItemBean("[c001apk]", R.drawable.ic_backspace))

        //4
        data.add(ItemBean("[挨打]", R.drawable.coolapk_emotion_1012))
        data.add(ItemBean("[捂嘴笑]", R.drawable.coolapk_emotion_24_wuzuixiao))
        data.add(ItemBean("[捂脸]", R.drawable.coolapk_emotion_33_wulian))
        data.add(ItemBean("[掩面笑]", R.drawable.coolapk_emotion_1018))
        data.add(ItemBean("[撇嘴]", R.drawable.coolapk_emotion_8_piezui))
        data.add(ItemBean("[斗鸡眼滑稽]", R.drawable.coolapk_emotion_66_doujiyanhuaji))
        data.add(ItemBean("[新币1分]", R.drawable.coolapk_emotion_72))
        data.add(ItemBean("[新酷币1$]", R.drawable.coolapk_emotion_75))
        data.add(ItemBean("[新酷币100块]", R.drawable.coolapk_emotion_74))
        data.add(ItemBean("[新酷币10块]", R.drawable.coolapk_emotion_93))
        data.add(ItemBean("[新酷币1€]", R.drawable.coolapk_emotion_78))
        data.add(ItemBean("[新酷币1分]", R.drawable.coolapk_emotion_72))
        data.add(ItemBean("[新酷币1块]", R.drawable.coolapk_emotion_90))
        data.add(ItemBean("[新酷币1毛]", R.drawable.coolapk_emotion_87))
        data.add(ItemBean("[新酷币2$]", R.drawable.coolapk_emotion_76))
        data.add(ItemBean("[新酷币20块]", R.drawable.coolapk_emotion_94))
        data.add(ItemBean("[新酷币2€]", R.drawable.coolapk_emotion_79))
        data.add(ItemBean("[新酷币2分]", R.drawable.coolapk_emotion_85))
        data.add(ItemBean("[新酷币2块]", R.drawable.coolapk_emotion_91))
        data.add(ItemBean("[新酷币2毛]", R.drawable.coolapk_emotion_88))
        data.add(ItemBean("[c001apk]", R.drawable.ic_backspace))

        //5
        data.add(ItemBean("[新酷币5$]", R.drawable.coolapk_emotion_77))
        data.add(ItemBean("[新酷币50块]", R.drawable.coolapk_emotion_73))
        data.add(ItemBean("[新酷币5€]", R.drawable.coolapk_emotion_80))
        data.add(ItemBean("[新酷币5分]", R.drawable.coolapk_emotion_86))
        data.add(ItemBean("[新酷币5块]", R.drawable.coolapk_emotion_92))
        data.add(ItemBean("[新酷币5毛]", R.drawable.coolapk_emotion_89))
        data.add(ItemBean("[新酷币]", R.drawable.coolapk_emotion_71))
        data.add(ItemBean("[无奈]", R.drawable.coolapk_emotion_98_wunai))
        data.add(ItemBean("[无语]", R.drawable.coolapk_emotion_12_wuyu))
        data.add(ItemBean("[机智]", R.drawable.coolapk_emotion_34_jizhi))
        data.add(ItemBean("[欢呼]", R.drawable.coolapk_emotion_49_huanhu))
        data.add(ItemBean("[汗]", R.drawable.coolapk_emotion_18_han))
        data.add(ItemBean("[流汗滑稽]", R.drawable.coolapk_emotion_63_liuhanhuaji))
        data.add(ItemBean("[流泪]", R.drawable.coolapk_emotion_4_liulei))
        data.add(ItemBean("[滑稽]", R.drawable.coolapk_emotion_62_huaji))
        data.add(ItemBean("[火把]", R.drawable.coolapk_emotion_83_huoba))
        data.add(ItemBean("[灰色酷币]", R.drawable.coolapk_emotion_68))
        data.add(ItemBean("[爆怒]", R.drawable.coolapk_emotion_104))
        data.add(ItemBean("[爱心]", R.drawable.coolapk_emotion_40_aixin))
        data.add(ItemBean("[牛啤]", R.drawable.coolapk_emotion_103_nb))
        data.add(ItemBean("[c001apk]", R.drawable.ic_backspace))

        //6
        data.add(ItemBean("[玫瑰]", R.drawable.coolapk_emotion_41_meigui))
        data.add(ItemBean("[疑问]", R.drawable.coolapk_emotion_11_yiwen))
        data.add(ItemBean("[白眼]", R.drawable.coolapk_emotion_84_baiyan))
        data.add(ItemBean("[白纹酷币]", R.drawable.coolapk_emotion_70))
        data.add(ItemBean("[皱眉]", R.drawable.coolapk_emotion_99_zhoumei))
        data.add(ItemBean("[真正的音乐]", R.drawable.coolapk_emotion_1024))
        data.add(ItemBean("[睡]", R.drawable.coolapk_emotion_23_shui))
        data.add(ItemBean("[笑哭]", R.drawable.coolapk_emotion_31_xiaoku))
        data.add(ItemBean("[笑眼]", R.drawable.coolapk_emotion_22_xiaoyan))
        data.add(ItemBean("[红药丸]", R.drawable.coolapk_emotion_54_hongyaowan))
        data.add(ItemBean("[给我整一个]", R.drawable.coolapk_emotion_1026))
        data.add(ItemBean("[绿帽]", R.drawable.coolapk_emotion_96_kuanlvmao))
        data.add(ItemBean("[绿色酷币]", R.drawable.coolapk_emotion_69))
        data.add(ItemBean("[绿药丸]", R.drawable.coolapk_emotion_55_lvyaowan))
        data.add(ItemBean("[耐克嘴]", R.drawable.coolapk_emotion_81_naikezui))
        data.add(ItemBean("[耶]", R.drawable.coolapk_emotion_35_ye))
        data.add(ItemBean("[舒服]", R.drawable.coolapk_emotion_106))
        data.add(ItemBean("[色]", R.drawable.coolapk_emotion_9_se))
        data.add(ItemBean("[菜刀]", R.drawable.coolapk_emotion_39_caidao))
        data.add(ItemBean("[表面哭泣]", R.drawable.coolapk_emotion_1019))
        data.add(ItemBean("[c001apk]", R.drawable.ic_backspace))

        //7
        data.add(ItemBean("[表面开心]", R.drawable.coolapk_emotion_1020))
        data.add(ItemBean("[鄙视]", R.drawable.coolapk_emotion_14_bishi))
        data.add(ItemBean("[酷]", R.drawable.coolapk_emotion_36_ku))
        data.add(ItemBean("[酷安]", R.drawable.coolapk_emotion_60_kuan))
        data.add(ItemBean("[酷安土豆]", R.drawable.coolapk_emotion_1030))
        data.add(ItemBean("[酷安绿帽]", R.drawable.coolapk_emotion_96_kuanlvmao))
        data.add(ItemBean("[酷安钓鱼]", R.drawable.coolapk_emotion_1021))
        data.add(ItemBean("[酷币1$]", R.drawable.c_oned))
        data.add(ItemBean("[酷币100块]", R.drawable.c_oy))
        data.add(ItemBean("[酷币10块]", R.drawable.c_teny))
        data.add(ItemBean("[酷币1€]", R.drawable.c_oneo))
        data.add(ItemBean("[酷币1分]", R.drawable.c_onef))
        data.add(ItemBean("[酷币1块]", R.drawable.c_oney))
        data.add(ItemBean("[酷币1毛]", R.drawable.c_onem))
        data.add(ItemBean("[酷币2$]", R.drawable.c_twod))
        data.add(ItemBean("[酷币20块]", R.drawable.c_ty))
        data.add(ItemBean("[酷币2€]", R.drawable.c_twoo))
        data.add(ItemBean("[酷币2分]", R.drawable.c_twof))
        data.add(ItemBean("[酷币2块]", R.drawable.c_twoy))
        data.add(ItemBean("[酷币2毛]", R.drawable.c_twom))
        data.add(ItemBean("[c001apk]", R.drawable.ic_backspace))

        //8
        data.add(ItemBean("[酷币5$]", R.drawable.c_fived))
        data.add(ItemBean("[酷币50块]", R.drawable.c_fy))
        data.add(ItemBean("[酷币5€]", R.drawable.c_fiveo))
        data.add(ItemBean("[酷币5分]", R.drawable.c_fivef))
        data.add(ItemBean("[酷币5块]", R.drawable.c_fivey))
        data.add(ItemBean("[酷币5毛]", R.drawable.c_fivem))
        data.add(ItemBean("[酷币]", R.drawable.c_coolb))
        data.add(ItemBean("[针不戳]", R.drawable.coolapk_emotion_1022_zhenbuchuo))
        data.add(ItemBean("[阴险]", R.drawable.coolapk_emotion_45_yinxian))
        data.add(ItemBean("[难过]", R.drawable.coolapk_emotion_46_nanguo))
        data.add(ItemBean("[黑线]", R.drawable.coolapk_emotion_43_heixian))
        data.add(ItemBean("[cos滑稽]", R.drawable.coolapk_emotion_65_coshuaji))
        data.add(ItemBean("[c001apk]", R.drawable.ic_backspace))

        var count = 0
        repeat(7) {
            maps.add(data.subList(count * 21, (count + 1) * 21))
            count++
        }
        maps.add(data.subList(148, 160))
        return maps
    }

}